# Generated by Django 3.2 on 2022-01-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexlistclass',
            name='NumberOfUnits',
            field=models.IntegerField(default=1),
        ),
    ]
