# Generated by Django 3.2 on 2021-09-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='SettingsClass',
        ),
    ]
