# Generated by Django 3.2 on 2021-09-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_settings_settingsclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsclass',
            old_name='Age_Analysist',
            new_name='Age_Analysis',
        ),
        migrations.RenameField(
            model_name='settingsclass',
            old_name='Mayor_capital_Items_GL',
            new_name='Mayor_capital_Items_General_Ledger',
        ),
        migrations.RenameField(
            model_name='settingsclass',
            old_name='Repair_and_Maintenance_GL',
            new_name='Repair_and_Maintenance_General_Ledger',
        ),
        migrations.RenameField(
            model_name='settingsclass',
            old_name='Trail_balance_Monthly',
            new_name='Trial_balance_Monthly',
        ),
        migrations.RenameField(
            model_name='settingsclass',
            old_name='Trail_balance_Year_to_date',
            new_name='Trial_balance_Year_to_date',
        ),
    ]
