# Generated by Django 3.2 on 2021-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210909_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsclass',
            name='Complex',
            field=models.CharField(choices=[('5th On Brooklyn', '5th On Brooklyn'), ('Ashkelon', 'Ashkelon'), ('Avonlea', 'Avonlea'), (4, 'Birchleigh View'), (5, 'Birchpark'), (6, 'Birds View'), (7, 'Blueberry Lane'), (8, 'BMT Community'), (9, 'Bolder View'), (10, 'Boschendal Manor'), (11, 'Bridgetown'), (12, 'Camperdown'), (13, 'Caro Brooke'), (14, 'Columbus Gardens'), (15, 'Constantia Place'), (16, 'CPH Court'), (17, 'Daphne Heights'), (18, 'Dennehof'), (19, 'De Scheepen'), (20, 'Die Binnehuis'), (21, 'Drommedaris'), (22, 'Eden Gardens'), (23, 'Falcon Haven'), (24, 'Fielding Place'), (25, 'Founders View'), (26, 'Glen Eden Villas'), (27, 'Graceland Estates'), (28, 'Hadedahs'), (29, 'Hillside Estate'), (30, 'Ingwe'), (31, 'Kiaat'), (32, 'Kleyngeluk'), (33, 'Kwikstertjie'), (34, 'Larenso Hof'), (35, 'Loftus View'), (36, 'Manhatten Heights'), (37, 'Monte Limar'), (38, 'Netosha Place'), (39, 'Nettleton Close'), (40, 'Oak Tree Village'), (41, 'Poltin Court'), (42, 'Rapallo'), (43, 'Rhino Industrial Park'), (44, 'River Close'), (45, 'Robins Place'), (46, 'Round About'), (47, 'Ruddell Gardens'), (48, 'Saligna'), (49, 'Sandpipers Nest'), (50, 'San La Meer'), (51, 'Stone Arch - Village 5'), (52, 'Sunnyside Terrace'), (53, 'Sunridge'), (54, 'Swallows Nest'), (55, 'The Drommedaris'), (56, 'Tulbagh Gardens'), (57, 'Victoria Court'), (58, 'Villa De Monte Negro'), (59, 'Villa Grove'), (60, 'Villa Izanie'), (61, 'Villa Marina'), (62, 'Walthof'), (63, 'Windmills'), (64, 'Zeldre Place')], default='1', max_length=15, unique=True),
        ),
    ]
