# Generated by Django 3.2 on 2021-09-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210915_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsclass',
            old_name='_tbm_Only_use_main_accounts',
            new_name='tbm_Only_use_main_accounts',
        ),
        migrations.RenameField(
            model_name='settingsclass',
            old_name='_tbm_Print_account',
            new_name='tbm_Print_account',
        ),
        migrations.RenameField(
            model_name='settingsclass',
            old_name='_tbm_Print_description',
            new_name='tbm_Print_description',
        ),
        migrations.RenameField(
            model_name='settingsclass',
            old_name='_tbm_Print_null_values',
            new_name='tbm_Print_null_values',
        ),
        migrations.RenameField(
            model_name='settingsclass',
            old_name='_tbm_Sort_by_account_name',
            new_name='tbm_Sort_by_account_name',
        ),
    ]
